import 'dart:convert';

import 'package:common/database/tables/tables.dart';
import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import '../datamodel/divination_request_info_datamodel.dart';
import '../datamodel/divination_type_data_model.dart';
import '../datamodel/location.dart';
import '../datamodel/seeker_model.dart';
import '../datamodel/sub_divination_type_data_model.dart';
import '../datamodel/timing_divination_model.dart';
import '../enums/enum_datetime_type.dart';
import '../enums/enum_gender.dart';
import '../enums/enum_jia_zi.dart';
import '../enums/enum_panel_type.dart';
import '../models/divination_datetime.dart';
import '../models/layout_template.dart';
import 'connection.dart' as impl;
import 'converters/nullable_location_converter.dart';
import 'converters/divination_datetime_model_converter.dart';

import 'daos/combined_divinations_dao.dart';
import 'daos/divination_panel_mappers_dao.dart';
import 'daos/divination_sub_divination_type_mappers_dao.dart';
import 'daos/divination_types_dao.dart';
import 'daos/divinations_dao.dart';
import 'daos/panel_skill_class_mappers_dao.dart';
import 'daos/panels_dao.dart';
import 'daos/seeker_divination_mappers_dao.dart';
import 'daos/seekers_dao.dart';
import 'daos/skill_classes_dao.dart';
import 'daos/skills_dao.dart';
import 'daos/timing_divinations_dao.dart';
import 'daos/layout_templates_dao.dart';
import 'daos/card_template_skill_usage_dao.dart';
import 'daos/card_template_meta_dao.dart';
import 'daos/card_template_setting_dao.dart';
import 'daos/market_template_installs_dao.dart';

// import 'daos/app_daos.dart';
// Generated by drift_dev when running `build_runner build`
part 'app_database.g.dart';

@DriftDatabase(
  tables: [
    Skills,
    SkillClasses,
    LayoutTemplates,
    CardTemplateMetas,
    CardTemplateSettings,
    CardTemplateSkillUsages,
    MarketTemplateInstalls,
    CombinedDivinations,
    Divinations,
    Seekers,
    Panels,
    DivinationTypes,
    SubDivinationTypes,
    SeekerDivinationMappers,
    DivinationPanelMappers,
    PanelSkillClassMappers,
    DivinationSubDivinationTypeMappers,
    TimingDivinations,
  ],
  daos: [
    CombinedDivinationsDao,
    DivinationsDao,
    TimingDivinationsDao,
    PanelsDao,
    SkillsDao,
    SkillClassesDao,
    LayoutTemplatesDao,
    CardTemplateMetaDao,
    CardTemplateSettingDao,
    CardTemplateSkillUsageDao,
    MarketTemplateInstallsDao,
    DivinationTypesDao,
    SeekersDao,
    SeekerDivinationMappersDao,
    DivinationPanelMappersDao,
    PanelSkillClassMappersDao,
    DivinationSubDivinationTypeMappersDao,
  ],

  // include: {'sql.drift'}
)
class AppDatabase extends _$AppDatabase {
  AppDatabase([QueryExecutor? e, bool loadInitialData = true])
      : _loadInitialData = loadInitialData,
        super(
          e ??
              driftDatabase(
                name: 'app_database',
                native: const DriftNativeOptions(
                  databaseDirectory: getApplicationSupportDirectory,
                ),
                web: DriftWebOptions(
                  sqlite3Wasm: Uri.parse('sqlite3.wasm'),
                  driftWorker: Uri.parse('drift_worker.js'),
                  onResult: (result) {
                    if (result.missingFeatures.isNotEmpty) {
                      if (kDebugMode) {
                        debugPrint(
                          'Using ${result.chosenImplementation} due to unsupported '
                          'browser features: ${result.missingFeatures}',
                        );
                      }
                    }
                  },
                ),
              ),
        );

  final bool _loadInitialData;

  // AppDatabase.forTesting(DatabaseConnection super.connection);

  @override
  int get schemaVersion => 7;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
        if (_loadInitialData) {
          await _executeSqlScript('assets/sql/initial_data.sql');
        }
      },
      onUpgrade: (Migrator m, int from, int to) async {
        if (from < 2) {
          await m.createTable(layoutTemplates);
        }
        if (from < 3) {
          await m.createTable(cardTemplateSkillUsages);
        }
        if (from < 4) {
          await m.createTable(cardTemplateMetas);
        }
        if (from < 5) {
          await m.createTable(cardTemplateSettings);
        }
        if (from < 7) {
          await m.createTable(marketTemplateInstalls);
        }
      },
      beforeOpen: (details) async {
        // Make sure that foreign keys are enabled
        // await customStatement('PRAGMA foreign_keys = ON');

        if (details.wasCreated) {
          // Create a bunch of default values so the app doesn't look too empty
          // on the first start.
        }

        // This follows the recommendation to validate that the database schema
        // matches what drift expects (https://drift.simonbinder.eu/docs/advanced-features/migrations/#verifying-a-database-schema-at-runtime).
        // It allows catching bugs in the migration logic early.
        await impl.validateDatabaseSchema(this);
        // await impl.validateDatabaseSchema();

        await _seedPublicLayoutTemplatesIfMissing();
      },
    );
  }

  Future<void> _executeSqlScript(String scriptPath) async {
    final sqlScript = await rootBundle.loadString(scriptPath);
    final statements = sqlScript
        .split(';')
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();

    for (final statement in statements) {
      await customStatement(statement);
    }
  }

  Future<void> _seedPublicLayoutTemplatesIfMissing() async {
    const publicCollectionId = '__public_default__';

    final existing = await layoutTemplatesDao.getAllByCollection(
      publicCollectionId,
    );
    if (existing.isNotEmpty) return;

    const assetPaths = <String>[
      'assets/templates/default_template.json',
      'assets/templates/chinese/outbox_payload_ink_minimal.json',
      'assets/templates/chinese/outbox_payload_vermilion_palace.json',
      'assets/templates/chinese/outbox_payload_blue_porcelain.json',
      'assets/templates/chinese/outbox_payload_bamboo_green.json',
    ];

    final resolvedKeys = await _resolveAssetKeys(assetPaths);

    final templates = <LayoutTemplate>[];
    for (final path in assetPaths) {
      try {
        final raw = await _loadSeedAsset(resolvedKeys[path] ?? path);
        final decoded = jsonDecode(raw);
        if (decoded is! Map<String, dynamic>) continue;
        final templateObj = decoded['template'];
        if (templateObj is! Map) continue;
        final template = LayoutTemplate.fromJson(
          Map<String, dynamic>.from(templateObj as Map),
        ).copyWith(collectionId: publicCollectionId);
        templates.add(template);
      } catch (_) {
        continue;
      }
    }

    if (templates.isEmpty) return;
    await layoutTemplatesDao.upsertAllTemplates(templates);
  }

  Future<String> _loadSeedAsset(String relativePath) async {
    try {
      if (relativePath.startsWith('packages/common/')) {
        return rootBundle.loadString(relativePath);
      }
      return await rootBundle.loadString('packages/common/$relativePath');
    } catch (_) {
      return rootBundle.loadString(relativePath);
    }
  }

  Future<Map<String, String>> _resolveAssetKeys(
    List<String> desiredRelativePaths,
  ) async {
    try {
      final raw = await rootBundle.loadString('AssetManifest.json');
      final decoded = jsonDecode(raw);
      if (decoded is! Map<String, dynamic>) {
        return const <String, String>{};
      }

      final keys = decoded.keys.toList(growable: false);
      final resolved = <String, String>{};
      for (final desired in desiredRelativePaths) {
        final match = keys.firstWhere(
          (k) => k.endsWith(desired),
          orElse: () => '',
        );
        if (match.isNotEmpty) {
          resolved[desired] = match;
        }
      }
      return resolved;
    } catch (_) {
      return const <String, String>{};
    }
  }
}
