// Mocks generated by Mockito 5.4.6 from annotations
// in common/test/viewmodels/yun_liu_view_model_cache_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:common/enums.dart' as _i3;
import 'package:common/features/liu_yun/models/yun_liu_display_models.dart'
    as _i4;
import 'package:common/features/liu_yun/services/yun_liu_service.dart' as _i2;
import 'package:common/models/chinese_date_info.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [YunLiuService].
///
/// See the documentation for Mockito's code generation for more information.
class MockYunLiuService extends _i1.Mock implements _i2.YunLiuService {
  MockYunLiuService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<
      ({
        _i3.EnumTenGods ganGod,
        List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
        List<
            ({
              int age,
              _i3.EnumTenGods ganGod,
              List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
              List<_i4.LiuYueDisplayData> liuyue,
              _i3.JiaZi pillar,
              int year
            })> liunian,
        _i3.JiaZi pillar,
        int startAge,
        int startYear,
        int yearsCount
      })> calculateDaYunList({
    required DateTime? birthDateTime,
    required _i3.Gender? gender,
    required _i5.ChineseDateInfo? birthDateInfo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateDaYunList,
          [],
          {
            #birthDateTime: birthDateTime,
            #gender: gender,
            #birthDateInfo: birthDateInfo,
          },
        ),
        returnValue: <({
          _i3.EnumTenGods ganGod,
          List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
          List<
              ({
                int age,
                _i3.EnumTenGods ganGod,
                List<
                    ({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
                List<_i4.LiuYueDisplayData> liuyue,
                _i3.JiaZi pillar,
                int year
              })> liunian,
          _i3.JiaZi pillar,
          int startAge,
          int startYear,
          int yearsCount
        })>[],
      ) as List<
          ({
            _i3.EnumTenGods ganGod,
            List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
            List<
                ({
                  int age,
                  _i3.EnumTenGods ganGod,
                  List<
                      ({
                        _i3.TianGan gan,
                        _i3.EnumTenGods hiddenGods
                      })> hiddenGans,
                  List<_i4.LiuYueDisplayData> liuyue,
                  _i3.JiaZi pillar,
                  int year
                })> liunian,
            _i3.JiaZi pillar,
            int startAge,
            int startYear,
            int yearsCount
          })>);

  @override
  List<
      ({
        int age,
        _i3.EnumTenGods ganGod,
        List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
        List<_i4.LiuYueDisplayData> liuyue,
        _i3.JiaZi pillar,
        int year
      })> calculateLiuNianList({
    required int? startYear,
    required int? startAge,
    required _i3.TianGan? dayMaster,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateLiuNianList,
          [],
          {
            #startYear: startYear,
            #startAge: startAge,
            #dayMaster: dayMaster,
          },
        ),
        returnValue: <({
          int age,
          _i3.EnumTenGods ganGod,
          List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
          List<_i4.LiuYueDisplayData> liuyue,
          _i3.JiaZi pillar,
          int year
        })>[],
      ) as List<
          ({
            int age,
            _i3.EnumTenGods ganGod,
            List<({_i3.TianGan gan, _i3.EnumTenGods hiddenGods})> hiddenGans,
            List<_i4.LiuYueDisplayData> liuyue,
            _i3.JiaZi pillar,
            int year
          })>);

  @override
  List<_i4.LiuYueDisplayData> calculateLiuYueList(
    _i3.JiaZi? yearPillar,
    _i3.TianGan? dayMaster,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateLiuYueList,
          [
            yearPillar,
            dayMaster,
          ],
        ),
        returnValue: <_i4.LiuYueDisplayData>[],
      ) as List<_i4.LiuYueDisplayData>);

  @override
  List<_i4.LiuRiDisplayData> fetchLiuRiData(
    int? year,
    int? month,
    _i3.TianGan? dayMaster,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLiuRiData,
          [
            year,
            month,
            dayMaster,
          ],
        ),
        returnValue: <_i4.LiuRiDisplayData>[],
      ) as List<_i4.LiuRiDisplayData>);

  @override
  List<_i4.LiuShiDisplayData> fetchLiuShiData(
    int? year,
    int? month,
    int? day,
    _i3.TianGan? dayMaster,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLiuShiData,
          [
            year,
            month,
            day,
            dayMaster,
          ],
        ),
        returnValue: <_i4.LiuShiDisplayData>[],
      ) as List<_i4.LiuShiDisplayData>);
}
